default:

    DIR_PRINCIPAL           :    "~/sits.rep"
    METADATA_BASE_NAME      :    "metadata.JSON"
    GRAPH_BASE_NAME	    :	 "graph.txt"
    HASH_NAME : "checksum.txt"
    RDS_NAME : "rds_process.rds"
    RDS_PATH : "result/rds"
    FILE_PATH : "result/file"
    CLASSIFY_PROCESS_DIR_NAME : "classification"
    REPRODUCE_NAME : "reproduce"
